version: "3"
services:
  # mongo: 
  #   image: mongo:latest
  #   ports:
  #     - "2701:2701"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - "8088:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

